spring:
   application:
      name: Database-Service
   h2:
      console:
         enabled: true
         path: /h2-console
server:
   port: 8082
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka